<?php

declare(strict_types=1);

/**
 * Self-check for EncryptDatabasePassword — specifically that it does not
 * alter the password before encrypting it.
 *
 * A trim() here once silently changed any password with leading or
 * trailing whitespace before it was stored: it decrypted back to a
 * different string than what was typed in, and the database rejected it
 * every time with "access denied", giving no hint the password itself
 * had been the one that was wrong.
 *
 * Run it with
 *   ddev exec php packages/typovigil/Tests/EncryptDatabasePasswordTest.php
 */

require_once __DIR__ . '/../Classes/Service/SecretCipher.php';
require_once __DIR__ . '/../Classes/Hook/EncryptDatabasePassword.php';

use Maidemde\Typovigil\Hook\EncryptDatabasePassword;
use Maidemde\Typovigil\Service\SecretCipher;

$checks = 0;

function check(bool $condition, string $message): void
{
    global $checks;
    $checks++;
    if (!$condition) {
        fwrite(STDERR, "FAIL: {$message}\n");
        exit(1);
    }
}

$GLOBALS['TYPO3_CONF_VARS']['SYS']['encryptionKey'] = str_repeat('a', 96);

// Stand-ins for the two TYPO3 classes this hook touches, so it runs without
// a bootstrap: DataHandler only ever needs to be passed through here, and
// GeneralUtility::makeInstance() just needs to construct a plain class.
if (!class_exists(\TYPO3\CMS\Core\DataHandling\DataHandler::class)) {
    eval('namespace TYPO3\CMS\Core\DataHandling; class DataHandler {}');
}
if (!class_exists(\TYPO3\CMS\Core\Utility\GeneralUtility::class)) {
    eval('namespace TYPO3\CMS\Core\Utility; class GeneralUtility { public static function makeInstance(string $class) { return new $class(); } }');
}

$hook = new EncryptDatabasePassword();
$dataHandler = new \TYPO3\CMS\Core\DataHandling\DataHandler();
$cipher = new SecretCipher();

// The case that broke: a generated password with a trailing space.
$withEdgeWhitespace = 'p4ssw0rd generated by the platform ';
$fieldArray = ['db_password' => $withEdgeWhitespace];
$hook->processDatamap_postProcessFieldArray('update', 'tx_typovigil_project', 9, $fieldArray, $dataHandler);

check(
    $cipher->decrypt($fieldArray['db_password']) === $withEdgeWhitespace,
    'a password with trailing whitespace survives unchanged'
);

$withLeadingSpace = ' leading-space-password';
$fieldArray = ['db_password' => $withLeadingSpace];
$hook->processDatamap_postProcessFieldArray('update', 'tx_typovigil_project', 9, $fieldArray, $dataHandler);

check(
    $cipher->decrypt($fieldArray['db_password']) === $withLeadingSpace,
    'a password with leading whitespace survives unchanged'
);

// An already-encrypted value (every save where the field was not touched)
// must pass through untouched, not be encrypted a second time.
$fieldArray = ['db_password' => 'plaintext'];
$hook->processDatamap_postProcessFieldArray('update', 'tx_typovigil_project', 9, $fieldArray, $dataHandler);
$onceEncrypted = $fieldArray['db_password'];

$fieldArray = ['db_password' => $onceEncrypted];
$hook->processDatamap_postProcessFieldArray('update', 'tx_typovigil_project', 9, $fieldArray, $dataHandler);
check($fieldArray['db_password'] === $onceEncrypted, 'an already-encrypted value is not encrypted again');

// A different table, or a save that does not touch db_password, must be
// left alone entirely.
$fieldArray = ['title' => 'Example Project'];
$hook->processDatamap_postProcessFieldArray('update', 'tx_typovigil_project', 9, $fieldArray, $dataHandler);
check(!isset($fieldArray['db_password']), 'a save without db_password is untouched');

$fieldArray = ['db_password' => 'irrelevant'];
$hook->processDatamap_postProcessFieldArray('update', 'fe_users', 9, $fieldArray, $dataHandler);
check($fieldArray['db_password'] === 'irrelevant', 'a different table is left alone');

fwrite(STDOUT, "OK: {$checks} checks passed\n");
