name: typovigil/security-sources
title: LLL:EXT:typovigil_sitepackage/ContentBlocks/ContentElements/security-sources/language/labels.xlf:title
group: common
description: LLL:EXT:typovigil_sitepackage/ContentBlocks/ContentElements/security-sources/language/labels.xlf:description
prefixFields: true
prefixType: full
fields:
  - identifier: heading
    type: Text
    label: LLL:EXT:typovigil_sitepackage/ContentBlocks/ContentElements/security-sources/language/labels.xlf:heading.label
    default: 'Security Advisories'
  - identifier: sources
    type: Collection
    label: LLL:EXT:typovigil_sitepackage/ContentBlocks/ContentElements/security-sources/language/labels.xlf:sources.label
    labelField: label
    fallbackLabelFields:
      - composer_name
    minitems: 1
    fields:
      - identifier: composer_name
        type: Text
        label: LLL:EXT:typovigil_sitepackage/ContentBlocks/ContentElements/security-sources/language/labels.xlf:sources.composer_name.label
        description: LLL:EXT:typovigil_sitepackage/ContentBlocks/ContentElements/security-sources/language/labels.xlf:sources.composer_name.description
        required: true
      - identifier: label
        type: Text
        label: LLL:EXT:typovigil_sitepackage/ContentBlocks/ContentElements/security-sources/language/labels.xlf:sources.label_field.label
        description: LLL:EXT:typovigil_sitepackage/ContentBlocks/ContentElements/security-sources/language/labels.xlf:sources.label_field.description
